resources:
  containers:
  - container: ubuntu1404
    image: lightgbm/vsts-agent:ubuntu-14.04
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
#  container: ubuntu1404
  strategy:
    matrix:
      regular:
        TASK: regular
  steps:
  - script: |
      docker run hello-world
      docker run --rm -it kaggle/python
    displayName: 'Test docker'
