resources:
  containers:
  - container: ubuntu1404
    image: lightgbm/vsts-agent:ubuntu-14.04
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      regular:
        TASK: regular
  steps:
  - script: |
      docker run --rm kaggle/python /bin/bash -c "pip install pytest rgf_python && git clone https://github.com/RGF-team/rgf.git && cd rgf/python-package/tests && pytest test_rgf_python.py"
    displayName: 'Test docker'
